### ISSUE TITLE
Parser fails when a comment is at the end of the last line

### ISSUE THREAD

**Issue by TonyLo1** [opennars/OpenNARS-for-Applications#10]
Parser fails
-----------------
<a --> b>.                  // Comment
<EOF>

Parses correctly
---------------------
<a --> b>.
// Comment
<EOF>

After further investigation the failure condition is not clear as the following parses correctly:

<(coffee * juice) --> opposite>.
<([bad] * [good]) --> opposite>.
<juice --> [good]>.
//check for derivation 
<[good] --> (opposite /2 coffee)>? 	//Answer: <[good] --> (opposite /2 coffee)>.	
10
<coffee --> [bad]>?	
// Comment

but the below example does not:

<a --> b>.
//First comment		
<b --> c>.	//Second comment	
<a --> c>?
//Third comment

**Comment by TonyLo1** [comment]
ok, found why the following works:

<(coffee * juice) --> opposite>.
<([bad] * [good]) --> opposite>.
<juice --> [good]>.
//check for derivation
<[good] --> (opposite /2 coffee)>? //Answer: <[good] --> (opposite /2 coffee)>.
10
<coffee --> [bad]>?
// Comment

The comment has a valid statement embedded which the parser treats as input. Definitely not what was required here.

**Comment by patham9** [comment]
Comment lines, command lines and Narsese lines are supported, intermixed versions thereof in a single line isn't.
Not an issue in practice, thus closed.

**Comment by PtrMan** [comment]
Well I would like to have something like this too. It can be "more descriptive" for human.

**Comment by patham9** [comment]
If you want a comment, why not put it directly above it? It even looks cleaner:
```
//The cat is an animal
<cat --> animal>.
```
vs.:
```
<cat --> animal>. //The cat is an animal.
```
