### ISSUE TITLE
Overlap issue

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#102]
[r0b3@toshi OpenNARS-for-Applications]$ ./NAR shell
    <{(b * n)} --> x>.
    Input: <{(b * n)} --> x>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
    <{(a * n)} --> x>.
    Input: <{(a * n)} --> x>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
    Derived: <{(b * n)} --> {(a * n)}>. Priority=0.181698 Truth: frequency=1.000000, confidence=0.447514
    Derived: <{(a * n)} --> {(b * n)}>. Priority=0.181698 Truth: frequency=1.000000, confidence=0.447514
    Derived: <{(b * n)} <-> {(a * n)}>. Priority=0.181698 Truth: frequency=1.000000, confidence=0.447514
    Derived: <{(a * n)} <-> {(b * n)}>. Priority=0.181698 Truth: frequency=1.000000, confidence=0.447514
    Derived: <{(b * n) (a * n)} --> x>. Priority=0.245189 Truth: frequency=1.000000, confidence=0.810000
    Derived: <{(a * n) (b * n)} --> x>. Priority=0.245189 Truth: frequency=1.000000, confidence=0.810000
    Derived: <({(b * n)} & {(a * n)}) --> x>. Priority=0.213928 Truth: frequency=1.000000, confidence=0.810000
    Derived: <({(a * n)} & {(b * n)}) --> x>. Priority=0.213928 Truth: frequency=1.000000, confidence=0.810000
    Derived: <({(b * n)} ~ {(a * n)}) --> x>. Priority=0.022457 Truth: frequency=0.000000, confidence=0.810000
    Derived: <({(a * n)} ~ {(b * n)}) --> x>. Priority=0.022457 Truth: frequency=0.000000, confidence=0.810000
    Derived: <<{(b * n)} --> $1> =/> <{(a * n)} --> $1>>. Priority=0.162845 Truth: frequency=1.000000, confidence=0.447514
    1
    performing 1 inference steps:
    done with 1 additional inference steps.
    
    5
    performing 5 inference steps:
    Derived: <{(b * n)} <-> {(a * n)}>. Priority=0.035531 Truth: frequency=1.000000, confidence=0.402762
    Derived: <{(a * n)} --> {(a * n)}>. Priority=0.030402 Truth: frequency=1.000000, confidence=0.200269
    Derived: <{(a * n)} <-> {(b * n)}>. Priority=0.035527 Truth: frequency=1.000000, confidence=0.402762
    Derived: <{(a * n)} <-> {(b * n)}>. Priority=0.035524 Truth: frequency=1.000000, confidence=0.402762
    Derived: <(b * n) <-> (a * n)>. Priority=0.042450 Truth: frequency=1.000000, confidence=0.402762
    done with 5 additional inference steps.
    5
    performing 5 inference steps:
    Derived: <{(b * n)} <-> {(a * n)}>. Priority=0.035520 Truth: frequency=1.000000, confidence=0.402762
    Derived: <(a * n) <-> (b * n)>. Priority=0.042446 Truth: frequency=1.000000, confidence=0.402762
    Derived: <(a * n) <-> (b * n)>. Priority=0.009638 Truth: frequency=1.000000, confidence=0.362486
    Derived: <(a * n) <-> (b * n)>. Priority=0.009638 Truth: frequency=1.000000, confidence=0.362486
    Derived: <(b * n) <-> (a * n)>. Priority=0.009637 Truth: frequency=1.000000, confidence=0.362486
    Derived: <(b * n) <-> (a * n)>. Priority=0.009637 Truth: frequency=1.000000, confidence=0.362486
    Derived: <{(a * n)} <-> {(a * n)}>. Priority=0.005001 Truth: frequency=1.000000, confidence=0.180242
    done with 5 additional inference steps.
    5
    performing 5 inference steps:
    Derived: <{(a * n)} <-> {(a * n)}>. Priority=0.000810 Truth: frequency=1.000000, confidence=0.162218
    Derived: <(a * n) <-> (a * n)>. Priority=0.000968 Truth: frequency=1.000000, confidence=0.162218
    Derived: <(a * n) <-> (a * n)>. Priority=0.000185 Truth: frequency=1.000000, confidence=0.145996
    Derived: <(a * n) <-> (a * n)>. Priority=0.000185 Truth: frequency=1.000000, confidence=0.145996
    done with 5 additional inference steps.
it derives a axiom/tautology `Derived: <(a * n) <-> (a * n)>. Priority=0.000968 Truth: frequency=1.000000, confidence=0.162218` which a NAR shouldn't be able to do acording to NARS papers/books.

**Comment by patham9** [comment]
It's fine as it's not harmful to derive a statement which is true anyway.
These statements aren't very useful as well, so they tend to die off quickly.

**Comment by PtrMan** [comment]
"this is fine"(TM)<br />
it still pollutes the memory and everything

**Comment by PtrMan** [comment]
how should the conclusions get derived without overlap?

**Comment by patham9** [comment]
I finally had time to look at this. It uses 
```
<<{(b * n)} --> $1> ==> <{(a * n)} --> $1>>. 
```
deductively, though no worries it can't revise up the result due to the overlap.
Like Java OpenNARS, it doesn't check for overlap on deduction, to allow for recursive reasoning etc.
