### ISSUE TITLE
Missing Inference rule for NAL 3 decomposition

### ISSUE THREAD

**Issue by TonyLo1** [opennars/OpenNARS-for-Applications#104]
Both variants of the de-compositional form of this rule are missing:

R2( (M --> P), (M --> S), |-, (M --> (P | S)), Truth_Union )

Here is an example that highlights it:
*volume=100
(({$1} --> [birdlike]) ==> ({$1} --> ([feathered] | [fly]))).
({Tweety} --> [birdlike]).
10
({Tweety} --> [feathered])?

**Comment by patham9** [comment]
I agree, though the example is not quite right, the decomposition rule for this case is:
`R2( (M --> P), (M --> (S | P)), |-, (M --> S), Truth_DecomposeNPP )`
It's already in NAL3 branch in case you want to try it.
If you would have used & which probably is what you intended, master will already decompose it too.
I will leave the issue open till this inference rule will make it into master.

**Comment by patham9** [comment]
closed since it was already merged to master a few weeks ago
