### ISSUE TITLE
forgetting of high exp items

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#109]
<(b * cycle) --> TOPICWORD>. {1.0 0.299999999916316}
    <(b * energy) --> TOPICWORD>. {1.0 0.2999999662394476}
    <(b * cno) --> TOPICWORD>. {1.0 0.29999990822930384}
    <(b * mev) --> TOPICWORD>. {1.0 0.2999997505413843}
    <(b * sun) --> TOPICWORD>. {1.0 0.299962977058774}
    <(b * bethe) --> TOPICWORD>. {1.0 0.29972643541033367}
    <(b * cycles) --> TOPICWORD>. {1.0 0.29972643541033367}
    <(b * e) --> TOPICWORD>. {1.0 0.29972643541033367}
    <(b * two) --> TOPICWORD>. {1.0 0.2992563743470001}
    <(b * stars) --> TOPICWORD>. {1.0 0.2992563743470001}
    <(b * reaction) --> TOPICWORD>. {1.0 0.2992563743470001}
    <(b * cno-i) --> TOPICWORD>. {1.0 0.2992563743470001}
    <(b * one) --> TOPICWORD>. {1.0 0.29797861590027436}
    <(b * neutrinos) --> TOPICWORD>. {1.0 0.29797861590027436}
    <(b * first) --> TOPICWORD>. {1.0 0.29797861590027436}
    <(b * emitted) --> TOPICWORD>. {1.0 0.29797861590027436}
    <(b * weizsäcker) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * hydrogen) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * helium) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * nucleus) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * k) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * decay) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * cn-cycle) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * neutrino) --> TOPICWORD>. {1.0 0.29450530833337973}
    <(b * reactions) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * chain) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * temperature) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * dominant) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * catalytic) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * nitrogen) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * oxygen) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * positrons) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * away) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * around) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * source) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * approximately) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * produced) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * proposed) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * von) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * also) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * cold) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * years) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * total) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * momentum) --> TOPICWORD>. {1.0 0.2850638794896408}
    <(b * called) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * bethe–weizsäcker) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * known) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * fusion) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * convert) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * proton–proton) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * core) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * carbon) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * isotopes) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * catalysts) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * step) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * stable) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * electron) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * involved) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * annihilate) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * electrons) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * transformations) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * loop) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * mass) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * less) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * starts) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * temperatures) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * output) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * much) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * nuclei) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * process) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * carl) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * hans) --> TOPICWORD>. {1.0 0.2593994150290162}
    <(b * experimental) --> TOPICWORD>. {1.0 0.2593994150290162}

    50

    <?x --> electron>?
    <electron --> ?x>?
    <?x <-> electron>?
    10

questions aren't answered, question is answered if only relevant judgement is given

**Comment by patham9** [comment]
It's not designed to remember the most true inputs, but the most useful ones it has needed most often.
Usefulness also takes lastUsed into account to give new concepts a chance, else it would ignore new information after some time.
Due to this, if questioned about say the last few statements, it will answer nicely.
The disadvantage: it will mean that new concepts will be able to flood out older ones which aren't stable yet / haven't been used multiple times.
To reduce this effect, enter new information when it is less busy with processing previous events.
If I add 10 inference steps between your inputs, it answers all your questions! But questions about "further back" / closer to the beginning it will still not answer. Unless you enter some information multiple times, then the related concepts will have a higher chance to survive.

Though there might be ways to improve the forgetting strategy:
Maybe initial concept usefulness should negatively depend on complexity?
Maybe initial concept usefulness can depend on truth value additionally?
Feel free to try, if it will still be able to deal with new information properly and passes the tests, it will be great.
I will leave this issue open so we can discuss improvements to the default policy.

**Comment by PtrMan** [comment]
Another idea is to maintain multiple belief tables per concept with different scoring functions. Then it may retain information if it's in at least one table. This would be similar to multi-objective optimization.

**Comment by PtrMan** [comment]
Issue still stands when it's asked after giving it the data for a second article:

https://gist.github.com/PtrMan/261c3a4380398a84a05a86ca4e5f851a

The it doesn't answer the questions about the old knowledge.

**Comment by patham9** [comment]
The last appearance of electron is in line 117 and appearing just once while the last input happens at line 322. You are essentially not feeding the same data in again but some new "noise" in addition, making it even more difficult to retain what happened before. But even if you would feed all the inputs again it wouldn't help much in this case, as the relative frequency of the items would still be the same. 
Your example worked for me with the original input with a delay of 10 between inputs, making it less busy before new input is absorbed. But it will work generally better if relevant input appears more than once and more often as less relevant input, as this will give these concepts a lead in usefulness.
Generally: the system needs to be able to keep working on new input (ability to create new concepts even when the existing ones are stable / have a high use count, by taking lastUsed into account). And it needs to be able to retain what it needed most often and especially in goal achievement (high use count). Meaning so far forgetting is a function of useCount and lastUsed. Taking more factors into account would be possible, feel free to try adjusting the forgetting policy.

**Comment by patham9** [comment]
There was an issue with beliefs which didn't get their use count increased when used in inference, forgetting works better now and the above example is answered.

**Comment by PtrMan** [comment]
>the system needs to be able to keep working on new input (ability to create new concepts even when the existing ones are stable / have a high use count, by taking lastUsed into account). And it needs to be able to retain what it needed most often and especially in goal achievement (high use count). 

This is no excuse for buggy implementation or crappy policies (in general too).
