### ISSUE TITLE
Finishing v0.8.7

### ISSUE THREAD

**Issue by patham9** [opennars/OpenNARS-for-Applications#115]
- Memory export and import of the beliefs contained in the most k useful concepts in a format which will also easily be adoptable for OpenNARS.
- Allow to export concept&knowledge export into a networkX graph for which tools exist to visualize and analyze.
-  Explicit questions about the future and past with :/: and :\\: are now supported.

**Comment by patham9** [comment]
Good progress: https://github.com/opennars/OpenNARS-for-Applications/pull/116

**Comment by patham9** [comment]
only prediction_filter.py left

**Comment by patham9** [comment]
![prediction](https://user-images.githubusercontent.com/8284677/112771509-c5ae8e00-901b-11eb-9a43-2d7f72acbeab.png)
![note](https://user-images.githubusercontent.com/8284677/112771512-c9daab80-901b-11eb-8e97-eb1730a53722.png)

**Comment by patham9** [comment]
![pong](https://user-images.githubusercontent.com/8284677/112771520-d19a5000-901b-11eb-94cf-bb9d1a01b9de.png)

**Comment by patham9** [comment]
Mr. Mandelbrot emerged from categoryformationanddetection.nal :)
![man3](https://user-images.githubusercontent.com/8284677/112772698-c9451380-9021-11eb-8720-a46eeb9c7f19.png)

**Comment by patham9** [comment]
![school](https://user-images.githubusercontent.com/8284677/112772881-d1518300-9022-11eb-8cf2-299fd2da0bb7.png)
![toothbrush](https://user-images.githubusercontent.com/8284677/112772921-0c53b680-9023-11eb-999b-103120320fc0.png)

**Comment by mindbound** [comment]
What is the correct order of chaining for producing the graphs? I was attempting `./NAR shell < ./examples/nal/categoryformationanddetection.nal | python3 concepts_to_graph.py` and got only a blank graph window. TIA.

**Comment by patham9** [comment]
Sorry I didn't document the new scripts yet, will do so before releasing v0.8.7.
For now:
```./NAR shell InspectionOnExit < nalfile.nal | python3 concept_usefulness_filter.py 10 | python3 concepts_to_graph.py```
InspectionOnExit lets it print the concepts after processing the example file, and concept_usefulness_filter.py 10 selects only the top k useful concept, making the output graph way cleaner. Also grep can be used, like | grep "cat" |) before usefulness filter if it should show cat-related concepts only for instance.

**Comment by mindbound** [comment]
Thank you!

**Comment by patham9** [comment]
Grammar learning img for release msg:
![image](https://user-images.githubusercontent.com/8284677/114301809-d64c1300-9ab5-11eb-91ad-3003fabf6140.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/114302780-24631580-9aba-11eb-8ee5-9a271dab29eb.png)

**Comment by patham9** [comment]
![image](https://user-images.githubusercontent.com/8284677/114302794-3ba20300-9aba-11eb-9399-02e5e6ef7997.png)
