### ISSUE TITLE
Build Error (GCC 12.1.0 on x64)

### ISSUE THREAD

**Issue by automenta** [opennars/OpenNARS-for-Applications#201]
Compilation started:
/tmp/cca7tjcG.o: in function `Narsese_Test':
main.c:(.text+0x10d0): relocation truncated to fit: R_X86_64_PC32 against symbol `Narsese_atomNames' defined in .bss section in /tmp/ccjZlOux.o
/tmp/cca7tjcG.o: in function `Process_Args':
main.c:(.text+0x895f): relocation truncated to fit: R_X86_64_PC32 against symbol `PRINT_DERIVATIONS' defined in .bss section in /tmp/ccqpjU32.o
/tmp/ccr0hAk1.o: in function `Cycle_ProcessAndInferGoalEvents':
Cycle.c:(.text+0x12df): relocation truncated to fit: R_X86_64_PC32 against symbol `cycling_goal_events' defined in .bss section in /tmp/ccqpjU32.o
/tmp/ccr0hAk1.o: in function `Cycle_ProcessBeliefEvents':
Cycle.c:(.text+0x171b): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x1763): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x176e): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x1802): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x183e): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x18cf): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x1a16): relocation truncated to fit: R_X86_64_PC32 against symbol `concepts' defined in .bss section in /tmp/ccqpjU32.o
Cycle.c:(.text+0x1ac6): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status

**Comment by patham9** [comment]
Thank you for pointing it out! Can you please pull and try again?
It was essentially the issue https://github.com/opennars/OpenNARS-for-Applications/issues/199
which is resolved for now.

**Comment by automenta** [comment]
works now. thanks
