### ISSUE TITLE
Linear Confidence Discount in Truth Fn's by Inner w2c/c2w Transform

### ISSUE THREAD

**Issue by automenta** [opennars/OpenNARS-for-Applications#223]
currently 
```deduction.c =  (T.c * B.c) * B.f```
how would differ from: 
```deduction.c = w2c(c2w(T.c * B.c) * B.f)```

in other words, when ever a truth function multiplies (discounts) confidence by a factor, it is possible to instead convert to evidence scale before multiplying, then convert back to confidence scale.

**thus linear amounts of evidence are preserved rather than "curved" as they would if the multiplication happened directly in confidence scale**

**Comment by automenta** [comment]
in 'weak' truth functions (like Induction), the 'weakening' step may need to be applied first, before the linear discount.  i believe the opposite order, weakening applied as final step, is usually implemented, which further curves the result.

**Comment by patham9** [comment]
I discussed it with Pei, will show the results of the discussion soon. In short: the treatment would be perfect if the truth evaluations would be about the same statement but aren't. when you draw the Venn Diagram you will see the issue. Will upload it when I have time.

**Comment by patham9** [comment]
Closed for now but I will post the picture next week.
