### ISSUE TITLE
ARM: SSE not known

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#227]
gcc: error: unrecognized command-line option ‘-mfpmath=sse’
    gcc: error: unrecognized command-line option ‘-msse2’
    Error with SSE, hence compiling without SSE:

**Comment by patham9** [comment]
this is by design. It says "hence compiling without SSE" and succeeds.
If you have a better solution feel free to create a PR! :)

**Comment by PtrMan** [comment]
maybe it should use -march=simd
