### ISSUE TITLE
+ relation doesn't derive conclusion as expected

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#232]
<(<X --> ctx0> * <Y --> ctx0>) --> (+ VSIZE)>.
    5
    <(<Y --> ctx0> * <Z --> ctx0>) --> (+ VSIZE)>.
    50Input: <(<X --> ctx0> * <Y --> ctx0>) --> (+ VSIZE)>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
    performing 5 inference steps:
    done with 5 additional inference steps.
    Input: <(<Y --> ctx0> * <Z --> ctx0>) --> (+ VSIZE)>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
    Derived: <<(<X --> ctx0> * <Y --> ctx0>) --> (+ $1)> ==> <(<Y --> ctx0> * <Z --> ctx0>) --> (+ $1)>>. Priority=0.083890 Truth: frequency=1.000000, confidence=0.447514
    Derived: <<(<Y --> ctx0> * <Z --> ctx0>) --> (+ $1)> ==> <(<X --> ctx0> * <Y --> ctx0>) --> (+ $1)>>. Priority=0.083890 Truth: frequency=1.000000, confidence=0.447514
    Derived: <<(<X --> ctx0> * <Y --> ctx0>) --> (+ $1)> <=> <(<Y --> ctx0> * <Z --> ctx0>) --> (+ $1)>>. Priority=0.083890 Truth: frequency=1.000000, confidence=0.447514
    Derived: <<(<Y --> ctx0> * <Z --> ctx0>) --> (+ $1)> <=> <(<X --> ctx0> * <Y --> ctx0>) --> (+ $1)>>. Priority=0.083890 Truth: frequency=1.000000, confidence=0.447514
    Derived: (<(<X --> ctx0> * <Y --> ctx0>) --> (+ #1)> && <(<Y --> ctx0> * <Z --> ctx0>) --> (+ #1)>). Priority=0.104898 Truth: frequency=1.000000, confidence=0.810000
    Derived: (<(<Y --> ctx0> * <Z --> ctx0>) --> (+ #1)> && <(<X --> ctx0> * <Y --> ctx0>) --> (+ #1)>). Priority=0.104898 Truth: frequency=1.000000, confidence=0.810000
    Derived: (<(<X --> ctx0> * <Y --> ctx0>) --> (+ VSIZE)> && <(<Y --> ctx0> * <Z --> ctx0>) --> (+ VSIZE)>). Priority=0.104898 Truth: frequency=1.000000, confidence=0.810000

    performing 50 inference steps:
    Derived: (<(<Y --> ctx0> * <Z --> ctx0>) --> (+ VSIZE)> && <(<X --> ctx0> * <Y --> ctx0>) --> (+ VSIZE)>). Priority=0.019775 Truth: frequency=1.000000, confidence=0.729000
    done with 50 additional inference steps.

Expected behaviour: derive `<(<X --> ctx0> * <Z --> ctx0>) --> (+ VSIZE)>.`

**Comment by patham9** [comment]
<((X * ctx0) * (Y * ctx0)) --> (+ VSIZE)>.
<((X * ctx0) * (Z * ctx0)) --> (+ VSIZE)>.
100
<((X * ctx0) * (Z * ctx0)) --> (+ VSIZE)>?
is now answered.
