### ISSUE TITLE
<=> should implicitly derive ==>

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#233]
<B <=> C>.
    Input: <B <=> C>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
    Derived: <C <=> B>. Priority=0.452500 Truth: frequency=1.000000, confidence=0.810000

expected: `<B ==> C>.` etc. <br />
This should make some rules redudant too.

**Comment by patham9** [comment]
no need yet

**Comment by patham9** [comment]
if you need it, just add
R1( (S <=> P), |-, (S ==> P), Truth_StructuralIntersection )
