### ISSUE TITLE
TODO *query functionality

### ISSUE THREAD

**Issue by patham9** [opennars/OpenNARS-for-Applications#256]
Allow ***query truth_exp_threshold term**
to query for all answers above the truth expectation threshold.
This could allow to do queries such as:
*query 0.6 <{?1} --> [left]>? :|:
"List all the instance which are currently known to be on the left side with truth expectation > 0.6".

This is different to input question
<{?1} --> [left]>? :|:
which gives the most certain answer only with the most certain instance.

**Comment by patham9** [comment]
implemented https://github.com/opennars/OpenNARS-for-Applications/commit/da8cf53ebf3a8df351c540a15430c7c61f600041

**Comment by MinaGabriel** [comment]
this feature is an essential addition, I am testing it now

**Comment by patham9** [comment]
Please let me know how it goes! :)
Else I will reopen the issue & fix.
