### ISSUE TITLE
Unused global variable `Narsese_operatorNames`

### ISSUE THREAD

**Issue by ARCJ137442** [opennars/OpenNARS-for-Applications#270]
The global variable `Narsese_operatorNames` is decleared at

<https://github.com/opennars/OpenNARS-for-Applications/blob/226156aa21919fa1e491d8d882f12c88f35bf6dd/src/Narsese.h#L51>

and defined at

<https://github.com/opennars/OpenNARS-for-Applications/blob/226156aa21919fa1e491d8d882f12c88f35bf6dd/src/Narsese.c#L34>

but only used in `Narsese_INIT` with simple initialization:

<https://github.com/opennars/OpenNARS-for-Applications/blob/226156aa21919fa1e491d8d882f12c88f35bf6dd/src/Narsese.c#L673-L676>

Referred to [this GitHub Docs post](https://docs.github.com/en/search-github/github-code-search/about-github-code-search), I can't search `Narsese_operatorNames` in branches other than `master`.

Does this variable play a role elsewhere, or is it just a deprecated variable that was forgotten to delete?

**Comment by patham9** [comment]
Thank you for finding! :)
And since is your work, I commited it using your Github info I saw from the commit log, I hope that is fine:
https://github.com/opennars/OpenNARS-for-Applications/commit/06f14a32e2df759286b608a2e797a37c00975069
