### ISSUE TITLE
[wiki] Outdated code source on Narsese-Parser implementation

### ISSUE THREAD

**Issue by ARCJ137442** [opennars/OpenNARS-for-Applications#272]
The link can be seen on page [wiki/Narsese-Parser](https://github.com/opennars/OpenNARS-for-Applications/wiki/Narsese-Parser#Implementation):

```markdown
See https://github.com/opennars/OpenNARS-for-Applications/blob/master/src/Encode.c for the current implementation.
```

As far as I know, the current code of Narsese parser is actually in [`Narsese.c`](https://github.com/opennars/OpenNARS-for-Applications/blob/master/src/Narsese.c) now.
(Accurately in [line 35-450](https://github.com/opennars/OpenNARS-for-Applications/blob/5aa15b0d4ea468c5c5e3fbc29345de869d5cf0bd/src/Narsese.c#L35-L450))

This Markdown phrase may be useful:

```markdown
See https://github.com/opennars/OpenNARS-for-Applications/blob/master/src/Narsese.c for the current implementation.
```

(There seems to be no way to submit a pull request to a wiki page at present)

**Comment by patham9** [comment]
Hi! Thank you very much for pointing out the issue, I updated the Wiki page accordingly.
