### ISSUE TITLE
Could not found the function definition for `Memory_AddOperation`

### ISSUE THREAD

**Issue by ARCJ137442** [opennars/OpenNARS-for-Applications#279]
The declearation of `Memory_AddOperation` is here:

https://github.com/opennars/OpenNARS-for-Applications/blob/9954416ca1316bdb42ffe6c8e65b339c0c54ca95/src/Memory.h#L105

Searching result of it:

![image](https://github.com/user-attachments/assets/c066c1f4-1fe5-4793-bed0-85c4c2bd72b4)

Editor error:

![image](https://github.com/user-attachments/assets/20461071-c79c-4cc8-a342-dd0e42531048)

Further searching of `_AddOperation`:

![image](https://github.com/user-attachments/assets/82039ec2-0fae-425b-9b54-4b6fe85a6e08)

Maybe the function `Memory_AddOperation` is deprecated and has been migrated to `NAR_AddOperation`?

**Comment by patham9** [comment]
Thank you for spotting this dinosaur that goes back to when ONA was still "ANSNA".
https://github.com/patham9/ANSNA/commit/829b5b0d44c23e517a110ceadf1c59eee31b41c6#diff-72c9b19986eb0fa66e4aaf659b5d9a0b5ded0f27fba14d33a27527687155cfabR28
It was superseded by 
`void NAR_AddOperation(char *atomname, Action procedure);`

**Comment by ARCJ137442** [comment]
> Thank you for spotting this dinosaur that goes back to when ONA was still "ANSNA". [patham9/ANSNA@829b5b0#diff-72c9b19986eb0fa66e4aaf659b5d9a0b5ded0f27fba14d33a27527687155cfabR28](https://github.com/patham9/ANSNA/commit/829b5b0d44c23e517a110ceadf1c59eee31b41c6#diff-72c9b19986eb0fa66e4aaf659b5d9a0b5ded0f27fba14d33a27527687155cfabR28) It was superseded by `void NAR_AddOperation(char *atomname, Action procedure);`

Okay, got it ✓
Does the superseded function declaration need to be deleted? I can submit a PR to complete the issue if needed ;)
