### ISSUE TITLE
[bug] In the `Alien_Test`, the defender and the alien0 is only visualized in the left half of the ASCII world

### ISSUE THREAD

**Issue by ARCJ137442** [opennars/OpenNARS-for-Applications#290]
It can be located in here:

https://github.com/opennars/OpenNARS-for-Applications/blob/b9e41d1ebe4223b9dad9820d1ab7f40c4e7210db/src/system_tests/Alien_Test.h#L56

the width of the ASCII world is **`20`**, while the scaler of positions is **`10`**:

https://github.com/opennars/OpenNARS-for-Applications/blob/b9e41d1ebe4223b9dad9820d1ab7f40c4e7210db/src/system_tests/Alien_Test.h#L105-L107

May we need to shrink the visual width of the world, or double the scaler of positions?

The former just need to apply this patch:

```c
int szX = 10;
```

or the latter:

```c
//visualize:
int batX = defenderX*20;
int ballY = 5;
int ballX = alien0X*20;
```

**Comment by patham9** [comment]
The latter sounds good!
Thank you!

**Comment by patham9** [comment]
Applied [ARCJ137442](https://github.com/ARCJ137442)'s code:
https://github.com/opennars/OpenNARS-for-Applications/commit/9721d3b277ccf06d738c94715731640b18bed581
