### ISSUE TITLE
[bug] Inproper occurrence time indexed concepts after forgetting concept

### ISSUE THREAD

**Issue by ARCJ137442** [opennars/OpenNARS-for-Applications#292]
Using this feature in PR #291,
it can be seen by changing the config of ONA with `#define CONCEPTS_MAX 3` on this NAL inputs:

```ONA-input
a. :|:
b. :|:
c. :|:
*occurrence_time_index
```

## Before Changing: `#define CONCEPTS_MAX 16384`

![0ba39a7400b97f132665565169d7ba3](https://github.com/user-attachments/assets/9b666a1e-a9d4-47ff-b04d-7266323ecca3)

## After Changing: `#define CONCEPTS_MAX 3`

![74af512683fd147e364e2b3e8d303e4](https://github.com/user-attachments/assets/ec1881bf-04c4-4c40-b542-ec82328c928a)

## Possible Cause

This may be because concepts are actually stored in `PriorityQueue`, and the occurrence time index simply stores Pointers to the corresponding address.

If a `Concept` is forgotten in the priority queue, ONA's mechanism is to "ignore the address of the forgotten concept", i.e. make this part of the "forgotten concept" invalid (not to use);
But in the function `Memory_Conceptualize`, concepts are forgotten and the corresponding `HT_concepts` and `InvertedAtomIndex` (essentially a `HashTable<Key=Term, Value=LinkedList<Concept>>`) are cleared, but `OccurrenceTimeIndex` is not processed. Therefore, it will store forgotten concepts (actually invalid) in `OccurrenceTimeIndex`.

Perhaps it is a question of how to manage the value lifetime of `*Concept`s, where they are used and where they are removed.

## Potential Problem

The technical aspect of this problem is that forgotten concepts may appear at `OccurrenceTimeIndex`,
and when forgotten, the `OccurrenceTimeIndex` may stores outdated concepts (or, dangling Pointers).
If a new `Concept` is added to `PriorityQueue`, and `PriorityQueue` reuses memory space (in my opinion, this is enough for the entire ONA reasoner to be stored on the stack),
the concepts pointed to by the "pointers of outdated concepts" in `OccurrenceTimeIndex` will be overwritten.

Thus, the direct manifestation of the problem is: The "historical events (concepts)" stored at `OccurrenceTimeIndex` may undergo unexpected changes when forgetting concepts, causing its own "index of historical events" to become chaotic - a forgotten "archaic concept" suddenly becoming a more recent one. This will be directly reflected through `OccurrenceTimeIndex_GetKthNewestElement`;

This logic may continue to affect ONA's reasoning at the NAL-7 level during subsequent traverses of `OccurrenceTimeIndex`, which may produce unexpected reasoning results.

**Comment by patham9** [comment]
The occurrence time index is essentially a FIFO of concept references to concepts which had selected events from the PQ, this qualifies them for temporal compounding. It is true that by concept forgetting an entry will not refer to the same concept as before anymore.

**However it is not an issue:**
- When an element is taken from the index, lastSelectionTime is checked. For forgotten concepts this value is reset, which disqualifies the concept from temporal compounding. Hence the logic is not affected.
- Alternatively one could keep the index always updated but then it probably would need a linked list data structure to handle the updating efficiently. However in practice that will be slower than the current approach which uses a contiguous array of concept references, especially considering that the most recently selected concepts are usually not already forgotten (as they have a recent lastUsed value which raises their usefulness).

**Comment by patham9** [comment]
Closed as it is not an issue (see previous comment).
