### ISSUE TITLE
VMEntry crash

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#33]
Derived: <((((1_4 * 1_4) | (0_3 * 1_5)) ~ (0_3 * 0_3)) | (0_3 * 0_3)) --> (1_3Derived: <( (*( (1_31_4) >*.  :|: occurrenceTime=16603 Priority=0.000000 1_4Truth: frequency=0.000000, confidence=0.024336
) | (0_3 * 1_5)) ~ (0_3 * 0_3)) | (0_3 * 0_3)) <-> Derived: (<(1_3((( *1_4 1_3 * )1_4>. :|: occurrenceTime=16603 Priority=0.000000 Truth: frequency=0.000000, confidence=0.024336
) | (0_3 * 1_5)) ~ (0_3 * 0_3)) | (0_3 * VMEntry stack underflow
0_3Test failed.

happens with a not yet released SymVision test

**Comment by PtrMan** [comment]
full log of a run https://gist.github.com/PtrMan/e79b618ee6c3144f4164fa777b87e267

**Comment by patham9** [comment]
Can you provide a full Narsese file which shows the problem?
Judging by your file the issue seems wrong encodings like a missing parenthesis in your input.

**Comment by patham9** [comment]
also check "\0" as last byte when sending data to UDPNAR as you mentioned!

**Comment by patham9** [comment]
was caused by a coding error on the application's side, not ONA itself.
