### ISSUE TITLE
Possible issues with `Table_Add` function?

### ISSUE THREAD

**Issue by crlf0710** [opennars/OpenNARS-for-Applications#46]
I've just started learning, reading `Table_SantiyCheck` function, it seems that all Terms occurred in 
a `Table` should be different. However `Table_Add` function does not enforce this rule. It neither checks further if the term occurs as a later item when `same_term` is false, nor update the existing item when `same_term` is true.  It just adds the implication as a new item, which may cause it fail "sanity check" i  think? Am i missing something here?

By the way, i wonder if there's a Discord or Zullip or something for discussions.

**Comment by patham9** [comment]
Hi  crlf0710!
Table_Add is not supposed to check for term duplicates.
Term duplicates play a role when the table should also support revision for evidence summarization. Hence Table_AddAndRevise checks for duplicates, and uses Table_Add as a helper function.
Our communication channel is accessible via "good old" IRC (#nars @ freenode.net), and via riot.im as well (#nars:matrix.org)

**Comment by patham9** [comment]
Also we have a public email discussion group: https://groups.google.com/forum/#!forum/open-nars
I have now extended the readme with these communication channels.
