### ISSUE TITLE
Problem with UDPNAR on macOS

### ISSUE THREAD

**Issue by andrason** [opennars/OpenNARS-for-Applications#49]
I'm having some trouble with UDPNAR, but there might just be something I'm missing. The UDPNAR test seems to just stop (is it expecting a client?) And when I try toothbrush_demo.py it stops, seemingly expecting an answer from ONA that it isn't getting. Running on macOS.

Here's where it stops in the UDPNAR test:

`>>UDPNAR test start
//UDPNAR started!
Input: <(a &/ ^left) =/> g>. Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Input: a. :|: occurrenceTime=3 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
Input: g! :|: occurrenceTime=4 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000
decision expectation 0.791600 impTruth=(1.000000, 0.900000): future=0 <(a &/ ^left) =/> g>
Input: ^left. :|: occurrenceTime=4 Priority=1.000000 Truth: frequency=1.000000, confidence=0.900000

`

**Comment by patham9** [comment]
Thank you for the issue report! Ideally tests should just run through when executing ./NAR after compilation. In this case the OS's network permissions also important though, where different OS's have different defaults: is the UDP port 50001 open in your firewall? Luckily I have a Apple notebook around these days, so I can fix it in a few days in case that it's not simply a port allowance issue, but I remember it all worked there, so I guess the port settings are most likely the issue.

Also, as a side node, standard-I/O is the preferred way to run examples:
```./NAR shell < ./examples/nal/toothbrush.nal```
though this won't help if you are interested in using the UDP interface.

**Comment by patham9** [comment]
I was able to replicate the issue on Mac, and even after disabling the firewall on Mac the issue stillt persists. No idea why yet.

**Comment by andrason** [comment]
It's strange, I've found that UDPNAR only fails with ./NAR, so it's not really an issue for me. E.g. toothbrush_demo.py works fine, I had just made the wrong assumption that I should have an UDPNAR instance running, which is what caused the failure there.

**Comment by patham9** [comment]
toothbrush_demo.py starts its own Nar instance, so it doesn't need an extra NAR started. For the test case, the sender might need just a small delay to make sure it sends when the listener is already open, in which case it's just a test issue, which would be great, will try on Mac today.

**Comment by patham9** [comment]
Ok found, UDPNAR_Stop() does not terminate on Mac OS.
So it's not a big issue, will now make sure it can be stopped on Mac as well..

**Comment by patham9** [comment]
merged

**Comment by patham9** [comment]
For completeness: why not pthread_cancel? reason:  1. the socket needs to be cleaned up anyway. 2. Bionic (Android C lib) does not support pthread_cancel.
