### ISSUE TITLE
github topics

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#50]
Every good project should have topics such as:
* reasoner
* nal
* nars
* ai
etc.

**Comment by patham9** [comment]
What do you mean with topics? Do you mean Wiki entries or descriptions about these aspects in the readme?

**Comment by PtrMan** [comment]
https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by patham9** [comment]
thank you, done!
