### ISSUE TITLE
show err "unknown option: --gc-sections"   when build in mac

### ISSUE THREAD

**Issue by moketao** [opennars/OpenNARS-for-Applications#6]
do the build.sh ，and show err msg ：

```
First stage done, generating RuleTable.c now, and finishing compilation.
ld: unknown option: --gc-sections
collect2: error: ld returned 1 exit status

```
system：
**macos 10.15.2 (19C57)**

search google ，get some info，**clang disguise gcc** 。。。
need to change clang to gcc，but too hard，I failed。

**Comment by patham9** [comment]
Hi 破耳狼!

Feel free to remove these compile flags.
We also have a Portability branch where this has been fixed already, it
will be merged into master today or tomorrow.
Then it will compile and run on every platform (32 bit and 64 bit), with
GCC and Clang.

Best regards,
Patrick

Am Mi., 19. Feb. 2020 um 12:05 Uhr schrieb 破耳狼 <notifications@github.com>:

**Comment by patham9** [comment]
Portability branch to be merged today or tomorrow: https://github.com/opennars/OpenNARS-for-Applications/pull/5

**Comment by patham9** [comment]
Merged: https://github.com/opennars/OpenNARS-for-Applications/commit/550cecdc10ecb6ec4a24239af347d08fea1295c3
