### ISSUE TITLE
Doesn't compile on Cygwin anymore

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#72]
R0B3@DESKTOP /cygdrive/c/Users/R0B3/dir/github/OpenNARS-for-Applications
$ ./build.sh
rm: das Entfernen von 'NAR' ist nicht möglich: No such file or directory
rm: das Entfernen von 'src/RuleTable.c' ist nicht möglich: No such file or directory
src/Concept.c src/Cycle.c src/Decision.c src/Event.c src/FIFO.c src/Globals.c src/HashTable.c src/Implication.c src/Inference.c src/main.c src/Memory.c src/NAL.c src/NAR.c src/Narsese.c src/NetworkNAR/Metric.c src/NetworkNAR/UDP.c src/NetworkNAR/UDPNAR.c src/PriorityQueue.c src/Shell.c src/Stack.c src/Stamp.c src/Stats.c src/Table.c src/Term.c src/Truth.c src/Usage.c src/Variable.c
Compilation started:

R0B3@DESKTOP /cygdrive/c/Users/R0B3/dir/github/OpenNARS-for-Applications
$ ls

it doesn't emit a NAR.exe

**Comment by ccrock4t** [comment]
Anecdotally, I can compile on Cygwin with a fresh clone of the repository. I did need to install gcc-core packages during the Cygwin installation

**Comment by patham9** [comment]
@PtrMan: did your machine have sufficient ram? or did it segfault on rule generation due to out of mem?
Looks like an out of mem issue to me, as I don't see any compilation or linking errors in your output.

**Comment by PtrMan** [comment]
Are you kidding me? The machine has 10's of GB and it's pretty much idle.

Am Di., 30. Juni 2020 um 21:00 Uhr schrieb Patrick Hammer <
notifications@github.com>:

**Comment by patham9** [comment]
And why don't your build tools output any error?
It doesn't look like an ONA issue to me if your compiler doesn't even
generate a binary and also doesn't tell you why.

Best regards,
Patrick

Am Di., 30. Juni 2020 um 19:17 Uhr schrieb PtrMan <notifications@github.com
