### ISSUE TITLE
property similarity is not handled

### ISSUE THREAD

**Issue by PtrMan** [opennars/OpenNARS-for-Applications#73]
< y --> [bb] >.
< bb <-> z >.
< y --> [z] >?

**Comment by patham9** [comment]
Tagges as "good first issue", as anyone interested can identify the missing NAL inference rule from the book and add a line in NAL.h to make this case work as intended (also for extensional sets, the same rule is missing)
As you know so far we only included the inference rules we found most crucial, the inference rule language makes it possible to implement new rules easily (also for beginners), while in the Java version it demanded a lot of care.

**Comment by patham9** [comment]
Added, the corresponding rules are:
```
R2( ({M} --> P), (S <-> M), |-, ({S} --> P), Truth_Analogy )
R2( (P --> [M]), (S <-> M), |-, (P --> [S]), Truth_Analogy )
```
