### ISSUE TITLE
Abduction/induction swapped in NAL.h

### ISSUE THREAD

**Issue by ccrock4t** [opennars/OpenNARS-for-Applications#74]
It looks like definitions for NAL-1 abduction/induction are swapped in NAL.h

![image](https://user-images.githubusercontent.com/15344554/89208982-69c65f00-d58b-11ea-9bd0-8ceee8ea3f1c.png)
_NAL.h_

But the truth-value functions are swapped too, and since they are symmetric this probably calculates the inference correctly.

![image](https://user-images.githubusercontent.com/15344554/89209080-9bd7c100-d58b-11ea-9091-e04be579dc1c.png)
_Truth.c_

But this discrepancy can potentially cause some problem depending on how it's used

**Comment by patham9** [comment]
I agree this "double-swap" might be confusing though it's fine due to **f_abd(a,b)=f_ind(b,a)**. 
Thank you for reporting this, and free to create a PR to "unwind" it, else I can do before the next version release.

**Comment by patham9** [comment]
merged, will do it in the sensirmotor part too, then this can be closed.
Also:
@ccrock4t For some reason your user does not show up in the contributor list.
In case you want to appear there, please make sure the email you used for commiting is linked to your Github account!

**Comment by patham9** [comment]
solved by https://github.com/opennars/OpenNARS-for-Applications/pull/76
