### ISSUE TITLE
Evidential overlap in structural transformation preventing rule application

### ISSUE THREAD

**Issue by TonyLo1** [opennars/OpenNARS-for-Applications#9]
Following example fails to answer question
----------------------------------------------------------
<(coffee * juice) --> opposite>.
<([bad] * [good]) --> opposite>.
<juice --> [good]>.
//check for derivation 
<[good] --> (opposite /2 coffee)>? 	//Answer: <[good] --> (opposite /2 coffee)>.	
10
<coffee --> [bad]>?			//Answer: None

The above intermediate answer is: Answer: <coffee --> [bad]>. creationTime=8 Truth: frequency=1.000000, confidence=0.373020

Following does answer question but requires a manual entry to create a non-overlapping stamp
-----------------------------------------------------------------------------------------------------------------------------
<(coffee * juice) --> opposite>.
<([bad] * [good]) --> opposite>.
<juice --> [good]>.
//force new stamp by manual entry 
<[good] --> (opposite /2 coffee)>. {1.0 0.3}
100
<coffee --> [bad]>?

Answer: <coffee --> [bad]>. creationTime=41 Truth: frequency=1.000000, confidence=0.323546

Low confidence truth used to confirm not low truth value related.

There is an additional issue related to term reduction - the related term reduction ( <-> ) rules were disabled for the above test cases.

**Comment by PtrMan** [comment]
Should a implementation solve this with additional rules like in narjure or there be a special handling for the evidential overlap check?

**Comment by patham9** [comment]
Solved by https://github.com/opennars/OpenNARS-for-Applications/pull/16, needs 50 steps though not 10, which is still fast.

**Comment by patham9** [comment]
just to add explanation: it wasn't an evidental overlap issue, just aggressive statement reductions which are now identity rules. (when inheritance is reduced to similarity there would be no image transformation possible thereafter, unless rules for image transformations on similarity are added)
