### ISSUE TITLE
NAR-shell Eternal goals are not supported

### ISSUE THREAD

**Issue by wentz89** [opennars/OpenNARS-for-Applications#99]
I just tested the commands from [here](https://github.com/opennars/opennars/wiki/Natural-Language-Processing) and when I enter:
`(NARS --> chatty)!` the shell exits with:
Eternal goals are not supported
Test failed.
I tried it with different frequency / confident values, but with the same outcome.

Working on Ubuntu 20.04 / x86_64 / Kernel 5.4.0-48-generic

**Comment by patham9** [comment]
Eternal goals are intentionally not supported. ONA assumes a motivation system which periodically inputs current goals such as, in a robotic scenario, "increase battery level" when the battery level has reached problematic levels.
To replicate the example in the opennars Wiki, a goal event can be used instead:
```
(NARS --> chatty)! :|:
```

**Comment by wentz89** [comment]
Thanks for fast reply, I was looking around in the source code but wasn't sure what to look for.

**Comment by patham9** [comment]
You're welcome! The message comes from the corresponding assertion in Memory_AddEvent:
https://github.com/opennars/OpenNARS-for-Applications/blob/master/src/Memory.c#L402

**Comment by wentz89** [comment]
What would happen if I, remove the isEvent check in Narsese_Sentence()-Function, so that i could add eternal goals... or is this not a good idea :-P?

**Comment by patham9** [comment]
You mean if every event is parsed as non-eternal? It would be the same as adding ":|:" on input side.
Eternal goals are time-independent, a way I could see them supported would be to add a global goal buffer holding the highest truth & most recent eternal goals, and letting them generate non-eternal goal events of same content&truth periodically. The way they were handled in Java OpenNARS was broken, decision making is inherently time-dependent, letting eternal goals cause operations at any moment, breaks the system's ability to coordinate its actions taking current circumstances into account.

**Comment by wentz89** [comment]
I can see that it is not suitable to use eternal goals. However since eternal goals are not support and wont be in the future, the parser could automatically convert an eternal goal to a non-eternal. I was pretty confused when i played around in the NARS-shell and it would fail and close the shell every time i send a goal which is unpractical for new users (like I am).Or possibly instead of asserting eternal goals the parser could report that they are not supported, wont be processed and the user should convert them to non-eternals by adding ':|:'?

**Comment by patham9** [comment]
for reference: discussed further and resolved by https://github.com/opennars/OpenNARS-for-Applications/pull/103
